version: "3.0"

services:
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.0
    ports:
      - 9864:9864
      - 9870:9870
      - 8088:8088
      - 9000:9000
    volumes:
      - sources/:/usr/local/hadoop/share/hadoop/mapreduce/sources/
    # hostname: jose

volumes:
  sources: