version: "3.0"

services:
  hadoop-master:
    container_name: hadoop-master
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - ./hadoop_conf/:/usr/local/hadoop/etc/hadoop/
    # ports:
    #   - 50070:50070 # Name Node
    #   - 19888:19888 # Resource Manager
    #   - 8088:8088 # MapReduce JobHistory Server
    # networks:
    #   - hadoop_net
    network_mode: host
  
  hadoop-slave-1:
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - ./hadoop_conf/:/usr/local/hadoop/etc/hadoop/


  # hadoop-slave-2:
  #   image: sequenceiq/hadoop-docker:2.7.0
  #   volumes:
  #     - ./hadoop_conf/:/usr/local/hadoop/etc/hadoop/
    # networks:
    #   - hadoop_net
  
networks:
  hadoop_net:
    external:
      name: hadoop_net