version: "3.0"

services:
  hadoop-master:
    container_name: hadoop-master
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - ./hadoop/:/usr/local/hadoop/etc/hadoop/

  hadoop-slave-1:
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - ./hadoop/:/usr/local/hadoop/etc/hadoop/

  hadoop-slave-2:
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - ./hadoop/:/usr/local/hadoop/etc/hadoop/
